### ISSUE TITLE
[bug] Firefox Image Feed error - when image is clicked on the UI stops working properly

### ISSUE THREAD

**Issue by Duemellon** [melMass/comfy_mtb#44] opened 2023-08-02 17:52 UTC
### Describe the bug

When the image is clicked in Image Feed & brought to center screen I am unable to use the X or the <> brought up to navigate. I cannot close the image. Furthermore ComfyUI in background doesn't respond except the floating menu acts as if I'm grabbing it. 

When I refresh the session it works fine again until I click on any image from the Image Feed.

https://github.com/melMass/comfy_mtb/assets/113479041/01d8e12a-9ae7-443a-9655-bbad1342585e

### Reproduction

Launch ComfyUI in FF
Generate images
Try opening image in image feed

### Expected behavior

The X and <> in the UI work

### Platform and versions

```sh
Windows
FF (latest version)
ComfyUI latest version
```

### Console output

```sh
none
```

**Comment by melMass** [comment] 2023-08-02 18:31
This looks like an older version of the image feed from the screenshot and this specific issue was fixed in #34 I think.

My guess is that the web folder could not be symlinked so it copied it and is now out of sync.
I don't want to automate the deletion of this folder on update to avoid unwanted issues.

**Comment by EricRollei** [comment] 2023-08-03 10:22
Hi Mel,
I've been having problems with OOM browser issues on high-number generation batches. I'm using Chrome on Windows 11 machine.   When I have seen the problem occur the browser tab goes to a white screen with the error report.  The batch continues to completion on the console, however.  On refresh of the tab, I'll have whatever the default workflow loaded and not necessarily what I was working on come back.  For about a week I have been bothering Pythongrosssss about this because I thought it was his image feed, but I guess it could be yours as it has the "Load Session History" on it.   One other possibility is that the OOM errors I've had are potentially caused by the WAS Node Suite Image Save node with the show history set to "True".  I do know that if I close the image feed, I don't have the problem, but I've only see the OOM problem with both the Image Save node and the Image feed in use.     I have not figured out how to disable the image feed.  Even when I use the red X to close, it will pop back up when new images are generated.   Is there a config option or settings where I can turn it off?

**Comment by melMass** [comment] 2023-08-03 11:22
> I've been having problems with OOM browser issues on high-number generation batches. 

The image feed is not very optimized in that regard and will load the full size images, I never had OOM errors but did have massive slowdowns.

> For about a week I have been bothering Pythongrosssss about this because I thought it was his image feed, but I guess it could be yours as it has the "Load Session History" on it. 

Hehe so it was you! Pythongoss mentioned your case. The goal would be to just add the two things my fork does to pythongoss's directly (i.e the lightbox and the possibility to retrieve history after a browser reload), I will try to find the time soonish to PR something clean. 
Since my fork Pyhongoss's version is much cleaner. I think it's the first thing I did when I discovered comfy so I've learned a lot since too.

> I have not figured out how to disable the image feed. Even when I use the red X to close, it will pop back up when new images are generated. Is there a config option or settings where I can turn it off?

That should not be the case, can you check like my previous comment that you are actually using the latest version? Web extensions must be copied so I still did not find the best approach (on install it tries to create an alias/symlink but from the logs I've seen in the issues it doesn't seem to work well everywhere...). 
Btw now if you already have pythongoss's imagefeed installed mine would not load in favor of his ;)

**Comment by melMass** [comment] 2023-08-05 20:24
Closing to tidy up the issues, feel free to comment to reopen it if you still face the issue

**Closed by melMass** 2023-08-05 20:24 UTC
Labels: type: 🐛 bug, status: ℹ️ needs more info
