### ISSUE TITLE
[bug] ONNX version issue

### ISSUE THREAD

**Issue by Ferniclestix** [melMass/comfy_mtb#87] opened 2023-09-05 05:53 UTC
### Describe the bug

On a comfyUI portable install. I get this issue after installing with comfyUI manager.

I've tried manually installing tensorflow and it bugs comfyUI to the point I had to set up a fresh install. could use a hand.

### Expected behavior

Load all nodes. when installed using comfyUI manager.

### Platform and versions

```sh
Windows, ComfyUI Portable.
```

### Console output

```sh
[comfy_mtb] | STATUS -> Some nodes failed to load:
        Failed to import module faceswap because ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'
```

### Additional context

Been having major issues with mtb installs, some of the features would be very useful for things im doing with tutorials and animation.

**Comment by melMass** [comment] 2023-09-05 10:17
Hi,

On windows in order to have GPU support I use an older version of tensorflow since they dropped GPU support on native windows.

This leads to quite a few issues that I try to patch in the install but it's obviously not enough (a lot of issues are about this)

In your case though (the onnx error) I think it might be the python version (for now mtb is only working with 3.10.X and I'm working on 3.11 support).

If you can confirm your python version it would be useful

**Comment by Ferniclestix** [comment] 2023-09-05 11:26
Python 3.10.9

**Comment by rcoedo** [comment] 2023-09-09 10:04
If it helps, I get this error when installing (same python version as @Ferniclestix)

```
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\xxx\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\onnxruntime\\capi\\onnxruntime_providers_shared.dll'
 Consider using the `--user` option or check the permissions.
```

**Comment by melMass** [comment] 2023-09-09 12:13
Also a duplicate of #83 I guess

**Comment by ffdown** [comment] 2023-09-09 20:02
same trouble...

**Comment by roop03988** [comment] 2023-10-01 06:46
Some clue as commented here on this related issue https://github.com/melMass/comfy_mtb/issues/83

**Comment by melMass** [comment] 2023-10-04 13:06
Thanks, interesting.
I think there are two distinct issues here. The one @roop03988 linked to seems to indeed be related to the OPs issue, but @rcoedo your case is a bit different, it took me time to understand but my install script is trying to be smarter than needed and spawn threads... windows and pip don't like that and the file lock result in the issue you are seeing, I will have a fix for that this week

**Comment by melMass** [comment] 2023-10-10 10:19
Hi,

The problematic nodes are removed in the next version, more precisely they are optional, you can learn more about it in the readme where I link to alternatives: https://github.com/melMass/comfy_mtb#optional-nodes

**Closed by melMass** 2023-10-10 10:19 UTC
Labels: type: 🐛 bug, 🎭 Face nodes
