### ISSUE TITLE
[bug] ComfyUI becomes unresponsive when comfy_mtb extension is active

### ISSUE THREAD

**Issue by thiagojramos** [melMass/comfy_mtb#112] opened 2023-10-11 02:27 UTC
### Describe the bug

When the comfy_mtb extension is active, the ComfyUI interface doesn't show anything. Even after clean installations and running on an isolated Conda environment, the issue persists.

<details>
<summary>Prints</summary>

![2023-10-10 (23)](https://github.com/melMass/comfy_mtb/assets/45890502/49465555-aded-420c-a263-96939ad96714)
![2023-10-10 (24)](https://github.com/melMass/comfy_mtb/assets/45890502/4dceb39d-f22f-40e6-87f1-a0fb397a41dc)
![2023-10-10 (22)](https://github.com/melMass/comfy_mtb/assets/45890502/a7f1cec3-21a0-4a5a-a2ab-9a4aab5e2e13)
![2023-10-10 (21)](https://github.com/melMass/comfy_mtb/assets/45890502/2a12a89e-ca9a-46ff-8ff5-8aebbedd6ea0)
![2023-10-10 (20)](https://github.com/melMass/comfy_mtb/assets/45890502/0dd08cb4-b3b8-48e6-ba4b-1ed7eac81f26)
![2023-10-10 (18)](https://github.com/melMass/comfy_mtb/assets/45890502/b22bcd1c-896e-466d-9525-6342d7b4061c)
![2023-10-10 (16)](https://github.com/melMass/comfy_mtb/assets/45890502/6b45497d-33b8-427e-a2ad-19254bc7fa9a)
![2023-10-10 (15)](https://github.com/melMass/comfy_mtb/assets/45890502/dd698e8a-e460-4c7f-8aea-ff7aa60f2979)

</details>

### Reproduction

- Activate a fresh Conda environment (ComfyUI) with Python 3.10.
- Install the comfyui package and comfy_mtb extension.
- Launch ComfyUI.
- Expected Behavior:
- I expect the ComfyUI interface to work as usual, displaying all the available nodes.

### Actual Behavior:

- ComfyUI doesn't display any nodes, and I receive the following warning upon startup:

>/home/thiagojramos/miniconda3/envs/ComfyUI/lib/python3.10/site-packages/torchvision/transforms/
functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
warnings.warn(
[comfy_mtb] | INFO -> loaded 55 nodes successfully

### Troubleshooting Steps Taken:

- Reinstalled comfyui and comfy_mtb from scratch.
- Tested with just comfy_mtb active, as well as combinations of comfyui, comfy_mtb, and comfyui-manager.
- All dependencies were successfully installed during the reinstallation process.

### Expected behavior

I expect the ComfyUI interface to work as usual, displaying all the available nodes.

<details>
<summary>Working Behavior without comfy_mtb</summary>

![2023-10-10 (14)](https://github.com/melMass/comfy_mtb/assets/45890502/c9153029-0320-46df-a41b-e9c0fbd6ae9e)
![2023-10-10 (13)](https://github.com/melMass/comfy_mtb/assets/45890502/de2154aa-fe70-4b1c-bf1f-1bcff7c1e81d)
![2023-10-10 (12)](https://github.com/melMass/comfy_mtb/assets/45890502/b56bed31-2e1e-44ea-b202-f4439862a68f)
![2023-10-10 (9)](https://github.com/melMass/comfy_mtb/assets/45890502/dcec7f9a-2929-43d8-84e6-bed193acd50b)
![2023-10-10 (8)](https://github.com/melMass/comfy_mtb/assets/45890502/32cb4ba9-eb50-43df-ad45-ebb708c29e4b)
![2023-10-10 (7)](https://github.com/melMass/comfy_mtb/assets/45890502/2666595f-8e9e-4e86-875a-03edfc526824)
</details>

### Operating System

Windows (WSL2)

### Comfy Mode

Conda Venv

### Console output

```sh

(ComfyUI) thiagojramos@wsl2:/d/ComfyUI$ python main.py --normalvram
** ComfyUI start up time: 2023-10-10 22:45:56.593337

Prestartup times for custom nodes:
   0.1 seconds: /d/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 4096 MB, total RAM 15907 MB
xformers version: 0.0.23.dev645
[2023-10-10 22:46:02,565] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerat
or to cuda (auto detect)
2023-10-10 22:46:05.638351: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Un
able to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has al
ready been registered
2023-10-10 22:46:05.638454: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Una
ble to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has alr
eady been registered
2023-10-10 22:46:05.638495: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] U
nable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has
 already been registered
2023-10-10 22:46:05.650812: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlo
w binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with th
e appropriate compiler flags.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1050 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
### Loading: ComfyUI-Manager (V0.34)
### ComfyUI Revision: 1551 [be903eb2] | Released on '2023-10-10'
/home/thiagojramos/miniconda3/envs/ComfyUI/lib/python3.10/site-packages/torchvision/transforms/
functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is dep
recated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just nee
d to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[comfy_mtb] | INFO -> loaded 55 nodes successfuly

Import times for custom nodes:
   1.4 seconds: /d/ComfyUI/custom_nodes/ComfyUI-Manager
   2.9 seconds: /d/ComfyUI/custom_nodes/comfy_mtb

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /d/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json

```

### Additional context

- I've tested this issue using MS Edge on Windows 11 as well as the WSL2-installed version. Both show the same behavior.
- When I try to access 127.0.0.1:8188/mtb, it gets stuck in an eternal loading loop.
- After hitting the reset button to revert to ComfyUI's default workflow, an error pops up indicating that no nodes are loaded, not even the default ones.

### - List of my Conda environment packages:
[Conda-Packages.txt](https://github.com/melMass/comfy_mtb/files/12864180/Conda-Packages.txt)

### - ComfyUI Log:
[comfyui-logs-1696988391793.json](https://github.com/melMass/comfy_mtb/files/12864171/comfyui-logs-1696988391793.json)

**Comment by melMass** [comment] 2023-10-11 02:41
Thanks for the detailed report unfortunately it all looks right (install log and run log).
It's strange that there is no better stack trace in the web browser, can you show the content of stat_comfy.sh ? It should'nt change much but we never know. The web extensions are now loaded using the `WEB_DIRECTORY` (https://github.com/melMass/comfy_mtb/blob/5dfea51dd8db2a4829e559eadeda22374b51c8a4/__init__.py#L38) added in recent comfy versions, but I see that you are using the version from yesterday so it's not that, I'll try after updating comfy on my side in the meantime, as it's a new thing maybe something changed

**Comment by melMass** [comment] 2023-10-11 02:57
Nope it's not a comfy update I just updated to latest now

**Comment by thiagojramos** [comment] 2023-10-11 16:00
Hi @melMass,

Thanks for your quick response! Here is the content of my `start_comfy.sh` script:


```
#!/bin/bash

cd /d/ComfyUI
~/miniconda3/envs/ComfyUI/bin/python main.py --normalvram ##--enable-cors-header
```


This script is just a convenience for starting ComfyUI with some arguments. I should note that I've also tried running ComfyUI directly without this script, and the issue remains the same.

I'd like to add that this isn't a new issue for me; I've been experiencing it for quite some time, even when I was using a Conda environment on Windows.

I'm attaching two new screenshots:

One showing that all the other extensions work perfectly with ComfyUI.
Another showing that when I add comfy_mtb to the mix, nothing appears in the UI.
Also, I tried accessing 127.0.0.1:8188/mtb, and it just stays in an eternal loading loop. Before, the UI would be blank for about 7-10 minutes and then eventually load, but for the past few days, it doesn't load at all.

I appreciate you looking into this. If there's anything else you need from my end, feel free to ask!

<details>
<summary>Screenshots</summary>

![2023-10-11 (6)](https://github.com/melMass/comfy_mtb/assets/45890502/d85a042e-68ea-45d8-b4c1-6581582e8479)
![2023-10-11 (2)](https://github.com/melMass/comfy_mtb/assets/45890502/9e87282d-8bc0-4df6-be4e-9c2f18860492)

</details>

### Logs:
[comfyui.log](https://github.com/melMass/comfy_mtb/files/12872101/comfyui.log)
[comfyui.prev.log](https://github.com/melMass/comfy_mtb/files/12872102/comfyui.prev.log)

**Comment by melMass** [comment] 2023-10-11 22:25
Nothing strange on those logs, besides an impressive amount of extensions, there is probably some collision going on, but you mentioned to have tried with only mtb installed? That's very strange since if anything recent updates should have removed the unconventional approaches.

I will poke you here when #109 is merged since it will iron out recent changes even more, but I tested on different system, python 11 is now supported too. Although you seem to use bash in WSL I will try to see if  I can reproduce there

**Comment by melMass** [comment] 2023-11-04 15:29
It should now be resolved

**Closed by melMass** 2023-11-04 15:29 UTC
Labels: type: 🐛 bug, status: 🧹 needs triage
